site_name: LooperXX's wiki
theme:
    name: 'material' # name: 'readthedocs'
    language: 'zh'
    feature:
        tabs: true
    
nav:
    - Home: index.md
    - NLP:
        - 'Machine Reading Comprehension': 'Neural Reading Comprehension and beyond.md'
extra:
  search:
    language: 'en, zh'