# Project information
site_name: Science is interesting.
site_description: Looper's homepage
site_author: 'Looper - Xiao Xu'
site_url: 'https://looperxx.github.io/'
# site_dir: 'looperxx.github.io'
# Repository
repo_name: 'LooperXX/LooperXX.github.io'
repo_url: 'https://github.com/LooperXX/LooperXX.github.io'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Looper Xiao Xu'

nav:
  - Home: index.md
  - ML & DL:
    - 'Attention' : 'Attention.md'
    - 'Normalization' : 'Normalization.md' 
    - 'Concepts' : 'Concepts.md'
    - '花书经验法则' : '花书经验法则.md'
    - '经典网络' : '经典网络.md'
  - NLP:
      - 简介: 
        - '自然语言处理简介' : '自然语言处理简介.md'
        - 'NLP的巨人肩膀' : 'NLP的巨人肩膀.md'
      - 框架学习:
        - 'NCRF++' : 'NCRF++学习笔记.md'
      - 书籍笔记:
        - 'NLP Concepts' : 'NLP Concepts.md'  
        - 'NNDL 习题' : 'NNDL 习题.md'      
        - 'Machine Reading Comprehension': 'Neural Reading Comprehension and beyond.md'
      - 课程笔记:
        - 'CS224n-2019简介' : 'CS224n-2019 简介.md'
        - 'CS224n-2019作业笔记' : 'CS224n-2019-Assignment.md'
        - CS224n-2019学习笔记:
          - '01 Introduction and Word Vectors' : 'CS224n-2019-01-Introduction and Word Vectors.md'
          - '02 Word Vectors 2 and Word Senses' : 'CS224n-2019-02-Word Vectors 2 and Word Senses.md'
          - '03 Word Window Classification,Neural Networks, and Matrix Calculus' : 'CS224n-2019-03-Word Window Classification,Neural Networks, and Matrix Calculus.md'
          - '04 Backpropagation and Computation Graphs' : 'CS224n-2019-04-Backpropagation and Computation Graphs.md'
          - '05 Linguistic Structure Dependency Parsing' : 'CS224n-2019-05-Linguistic Structure Dependency Parsing.md'
          - '06 The probability of a sentence Recurrent Neural Networks and Language Models' : 'CS224n-2019-06-The probability of a sentence Recurrent Neural Networks and Language Models.md'
          - '07 Vanishing Gradients and Fancy RNNs' : 'CS224n-2019-07-Vanishing Gradients and Fancy RNNs.md'
          - '08 Machine Translation, Sequence-to-sequence and Attention' : 'CS224n-2019-08-Machine Translation, Sequence-to-sequence and Attention.md'
          - '09 Practical Tips for Final Projects' : 'CS224n-2019-09-Practical Tips for Final Projects.md'
          - '10 Question Answering and the Default Final Project' : 'CS224n-2019-10-Question Answering and the Default Final Project.md'
          - '11 ConvNets for NLP' : 'CS224n-2019-11-ConvNets for NLP.md'
          - '12 Information from parts of words Subword Models' : 'CS224n-2019-12-Information from parts of words Subword Models.md'
          - '13 Modeling contexts of use Contextual Representations and Pretraining' : 'CS224n-2019-13-Modeling contexts of use Contextual Representations and Pretraining.md'
          - '14 Transformers and Self-Attention For Generative Models' : 'CS224n-2019-14-Transformers and Self-Attention For Generative Models.md'
          - '15 Natural Language Generation' : 'CS224n-2019-15-Natural Language Generation.md'
          - '16 Coreference Resolution' : 'CS224n-2019-16-Coreference Resolution.md'
  - Interview experience:
    - '我的面经' : '面经.md'
    - 实训笔记:
      - 'Protobuf' : 'Protocol Buffers.md'
      - 'FDBus' : 'FDBus.md'
      - 'FDBus API' : 'FDBus API.md'
      - 'FDBus内部结构' : 'FDBus内部结构.md'
      - 'Cross compiler' : 'Cross compiler.md'
  - Math & CS & Coding:
    - 'Linux' : 'Linux.md'
    - 'CS专业课' : '专业知识面试准备.md'
    - '重点内容' : 'Coding Knowledge.md'
    - '历年机试' : '历年机试.md'
  - For MkDocs:
      - 'Demo' : 'MkDocs_demo.md'
      - 'Material Theme Tutorial' : 'Material Theme Tutorial.md'

theme:
  name: 'material' 
  # name: 'readthedocs'
  language: 'zh'
  # palette:
  #   primary: 'indigo'
  #   accent: 'indigo'
  # font:
  #   text: 'Roboto'
  #   code: 'Roboto Mono'
  feature:
      tabs: true
  # logo:
  #   icon: 'cloud'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/looperXX'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/%E5%95%B8-%E5%BE%90-012456163/'
  disqus: 'https-looperxx-github-io-my-wiki'
  search:
    language: 'jp'

# Extensions
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'js/baidu-tongji.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
